write() and close() do not fail, they raise exceptions.
I was wondering if it would be legal to simplify file handling here, because all this special casing did not look like Python to me.

I tried this:

# dd if=/dev/zero of=/tmp/testfile bs=1024k count=1
# mkfs -t ext2 /tmp/testfile
# mkdir a
# mount /tmp/testfile /a
 # df -Th /a
Filesystem     Type  Size  Used Avail Use% Mounted on
/dev/loop6     ext2  992K   24K  920K   3% /a

In there, I can now:

1. run out of space

# python3
Python 3.8.10 (default, Nov 26 2021, 20:14:08)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> with open("testfile", "w") as f:
...   f.write("a" * (1024*1024))
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
OSError: [Errno 28] No space left on device

2. have no permission to write for whatever reason (here: ro filesystem)

# umount /a
# mount -o ro /tmp/testfile /a
# cd /a
# python3
Python 3.8.10 (default, Nov 26 2021, 20:14:08)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> with open("testfile", "w") as f:
...   f.write("Keks")
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 30] Read-only file system: 'testfile'
>>>

From this, I believe it is okay to not write "Go"-like functions returning error codes, but just rely on Python raising appropriate exceptions when things catch file.

load_word_list_from_url() could even be returning bare (no return value, bare "return" instead of the pointless "return True").